---
format: 
  html:
    template-partials: ../../../custom/title-block.html
title: "Source Matters: Demand vs. Supply Uncertainty in a Small Open Economy"
author: 
  - Matthew DeHaven
# date:
categories: ["business cycles", "financial", "international"]
callout-important: "Job Market Paper"
# image: 
# pdf-url:
# external-url:
# external-name:
# citation:
#   type: article-journal
#   container-title:
#   volume:
#   issue:
#   page-first:
#   issn:
#   doi:
---


:::{.callout-important appearance="simple"}
## 2026-2027 Job Market Paper
Draft coming soon.
:::

# Abstract

How do domestic uncertainty shocks affect the macroeconomy and financial markets?
I study this question in a New Keynesian small open economy model with stochastic volatility and incomplete international risk sharing.
I find that in an open economy, the effects of domestic uncertainty shocks depend upon the source of uncertainty.
Domestic productivity uncertainty shocks lead to an increase in the foreign bond risk premium and an appreciation of the nominal exchange rate.
Domestic demand uncertainty shocks lead to a depreciation instead.
In data from the United Kingdom, I separate supply and demand uncertainty shocks and find they have opposite responses in the nominal exchange rate.
My model can account for this pattern with shocks to different sources of uncertainty.