project:
  type: website
  output-dir: docs
execute-dir: project

website:
  title: "Matthew DeHaven"
  favicon: static-content/logo/logo-32x32.png
  navbar:
    logo: static-content/logo/logo.svg
    left:
      - icon: person
        href: about.qmd
        text: About
      - icon: file-earmark-bar-graph
        href: research/index.qmd
        text: Research
      - icon: easel
        href: teaching/index.qmd
        text: Teaching
      - icon: file-earmark-pdf
        href: CV/index.qmd
        text: CV
    toggle-position: "right"
  page-footer:
    left: "[Source code](https://github.com/matdehaven/matdehaven.github.io)."
    center: © 2024  &middot; Created with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) .
    right:
      - href: https://github.com/matdehaven
        icon: github
format:
  html:
    include-in-header:
      text: <link rel="apple-touch-icon" sizes="180x180" href="/static-content/logo/apple-touch-icon.png">
    theme: 
      - simplex
      - custom-theme.scss
    toc: true

editor:
  render-on-save: true
