publishDir: docs/
theme: "hugo-PaperMod"
baseURL: http://matthewdehaven.com/
languageCode: en-us
title: Matthew DeHaven
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "(^|/)renv$", "renv\\.lock$"]
buildFuture: true

params:
    defaultTheme: light
    disableThemeToggle: true
    hideSummary: true
    hideDescription: false
    DateFormat: "January 2006"
    profileMode:
        enabled: true
        title: "Matthew DeHaven"
        subtitle: "I am a PhD student in economics at Brown University.  My interests are in macroeconomics, international finance, and monetary policy.  In particular, I hope to study the causes of recessions and financial crises, and the best policies to aid recoveries."
        imageUrl:  "profile-picture-square.png"
        imageTitle: Picture of Matthew
        imageWidth: 200 # Hexagon ratio
        imageHeight: 200
    socialIcons:
        - name: "CV"
          url: "./TestPDF.pdf"
        - name: "Github"
          url: "https://github.com/matdehaven"
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/matthew-dehaven-067856b6/"
        - name: "Google Scholar"
          url: "https://scholar.google.com/citations?user=q_4egM0AAAAJ&hl=en"
    label:
      text: Matthew DeHaven
      icon: "logo.png"
      iconheight: 32

menu:
  main:
    - identifier: About
      name: About Me
      url: /about/
      weight: 10
    - identifier: Research
      name: Research
      url: /research/
      weight: 20
    - identifier: Projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: Data
      name: Data
      url: /data/
      weight: 40
    - identifier: Archive
      name: Archive
      url: /archive/
      weight: 50


markup:
  goldmark:
    renderer:
      unsafe: true