---
title: "Applied Economics Analysis"
author: Matthew DeHaven
categories: ["graduate"]
---

A first year graduate course aimed to prepare students with practical skills for pursuing academic research.

My Role
: Course Designer and Instructor

[Course Website and Syllabus](https://matthewdehaven.com/course-applied-economics-analysis/){target="_blank"}

# Course Description

This course prepares students to conduct independent research by providing the necessary skills in programming and project organization. Topics covered will include version control, the Visual Studio Code IDE, programming basics, environments, functional programming, unit testing, data vizualization, data science, and more. Material will be presented using the programming language R, with some time spent on introductions to Python, Julia, and some basics of HTML. By the end of the course students should feel comfortable in the major programming languages used in economic research and in producing their own work as a replicable, sustainable project.

# Teaching Reviews

[Spring 2024](Spring2024ECON2020S01ECON2020Spring24S01AppliedEconomicsAnalysis-S01_MatthewDeHaven.pdf){target="_blank"}